export const symbols = {
  // numbers
  "1": "<i class=\"ms ms-1 ms-cost ms-shadow\"></i>",
  "2": "<i class=\"ms ms-2 ms-cost ms-shadow\"></i>",
  "3": "<i class=\"ms ms-3 ms-cost ms-shadow\"></i>",
  "4": "<i class=\"ms ms-4 ms-cost ms-shadow\"></i>",
  "5": "<i class=\"ms ms-5 ms-cost ms-shadow\"></i>",
  "6": "<i class=\"ms ms-6 ms-cost ms-shadow\"></i>",
  "7": "<i class=\"ms ms-7 ms-cost ms-shadow\"></i>",
  "8": "<i class=\"ms ms-8 ms-cost ms-shadow\"></i>",
  "9": "<i class=\"ms ms-9 ms-cost ms-shadow\"></i>",
  "10": "<i class=\"ms ms-10 ms-cost ms-shadow\"></i>",
  "11": "<i class=\"ms ms-11 ms-cost ms-shadow\"></i>",
  "12": "<i class=\"ms ms-12 ms-cost ms-shadow\"></i>",
  "13": "<i class=\"ms ms-13 ms-cost ms-shadow\"></i>",
  "14": "<i class=\"ms ms-14 ms-cost ms-shadow\"></i>",
  "15": "<i class=\"ms ms-15 ms-cost ms-shadow\"></i>",
  "16": "<i class=\"ms ms-16 ms-cost ms-shadow\"></i>",
  "17": "<i class=\"ms ms-17 ms-cost ms-shadow\"></i>",
  "18": "<i class=\"ms ms-18 ms-cost ms-shadow\"></i>",
  "19": "<i class=\"ms ms-19 ms-cost ms-shadow\"></i>",
  "20": "<i class=\"ms ms-20 ms-cost ms-shadow\"></i>",
  "X": "<i class=\"ms ms-x ms-cost ms-shadow\"></i>",
  "Y": "<i class=\"ms ms-y ms-cost ms-shadow\"></i>",
  "Z": "<i class=\"ms ms-z ms-cost ms-shadow\"></i>",

  // colours and adjacent
  "W": "<i class=\"ms ms-w ms-cost ms-shadow\"></i>",
  "U": "<i class=\"ms ms-u ms-cost ms-shadow\"></i>",
  "B": "<i class=\"ms ms-b ms-cost ms-shadow\"></i>",
  "R": "<i class=\"ms ms-r ms-cost ms-shadow\"></i>",
  "G": "<i class=\"ms ms-g ms-cost ms-shadow\"></i>",
  "C": "<i class=\"ms ms-c ms-cost ms-shadow\"></i>",
  "S": "<i class=\"ms ms-s ms-cost ms-shadow\"></i>",
  "W/U": "<i class=\"ms ms-wu ms-cost ms-shadow\"></i>",
  "W/B": "<i class=\"ms ms-wb ms-cost ms-shadow\"></i>",
  "U/B": "<i class=\"ms ms-ub ms-cost ms-shadow\"></i>",
  "U/R": "<i class=\"ms ms-ur ms-cost ms-shadow\"></i>",
  "B/R": "<i class=\"ms ms-br ms-cost ms-shadow\"></i>",
  "B/G": "<i class=\"ms ms-bg ms-cost ms-shadow\"></i>",
  "R/W": "<i class=\"ms ms-rw ms-cost ms-shadow\"></i>",
  "R/G": "<i class=\"ms ms-rg ms-cost ms-shadow\"></i>",
  "G/W": "<i class=\"ms ms-gw ms-cost ms-shadow\"></i>",
  "G/U": "<i class=\"ms ms-gu ms-cost ms-shadow\"></i>",
  "2/W": "<i class=\"ms ms-2w ms-cost ms-shadow\"></i>",
  "2/U": "<i class=\"ms ms-2u ms-cost ms-shadow\"></i>",
  "2/B": "<i class=\"ms ms-2b ms-cost ms-shadow\"></i>",
  "2/R": "<i class=\"ms ms-2r ms-cost ms-shadow\"></i>",
  "2/G": "<i class=\"ms ms-2g ms-cost ms-shadow\"></i>",
  "W/P": "<i class=\"ms ms-wp ms-cost ms-shadow\"></i>",
  "U/P": "<i class=\"ms ms-up ms-cost ms-shadow\"></i>",
  "B/P": "<i class=\"ms ms-bp ms-cost ms-shadow\"></i>",
  "R/P": "<i class=\"ms ms-rp ms-cost ms-shadow\"></i>",
  "G/P": "<i class=\"ms ms-gp ms-cost ms-shadow\"></i>",

  // other costs
  "T": "<i class=\"ms ms-tap ms-cost ms-shadow\"></i>",
  "Q": "<i class=\"ms ms-untap ms-cost\"></i>",
  "E": "<i class=\"ms ms-e\"></i>",
};